### ISSUE TITLE
Not working on Firefox

### ISSUE THREAD

**Issue by cyrobmm** [shaekuronen/jquery.flexloader#1] opened 2014-04-27 05:33 UTC
It's working good on Chrome but on Firefox just the demo Flexslider Slideshow (no Flexloader) is working. I wish I could give you some help about the issue but I couldn't understand the problem.

It's looking great. Thanks for the awesome plugin.

**Comment by shaekuronen** [comment] 2014-04-27 13:40
Can you get me the os + browser version that the issue is on?

Just tested the [demos](http://shaekuronen.github.io/jquery.flexloader/) on osx 10.9 + win 7, 8, 8.1 Firefox 28 and am not seeing any issues

Definitely want to make this plugin bulletproof, thanks for filing the bug!

**Comment by cyrobmm** [comment] 2014-04-27 16:10
I'm having problems on OS X 10.9.2 (http://screencloud.net/v/gW64) with Firefox 28 (http://screencloud.net/v/dxn6 and http://screencloud.net/v/yrzl).

You are welcome!

Keep up the good work.

**Comment by shaekuronen** [comment] 2014-04-27 17:19
Looks like this might be a known Flexslider issue [#958](https://github.com/woothemes/FlexSlider/issues/958), though it's strange you're seeing the default Flexslider work, but none of the Flexloader versions.

Could you try the solution proposed by @stevenaanen [here](https://github.com/woothemes/FlexSlider/issues/958/#issuecomment-37100431)?

I'm also on 10.9.2 FF 28 but am not seeing the issue, so FF config a possibility

Hmm, might be worth testing on another version of FF.  Do you have time to try the [nightly build](http://nightly.mozilla.org/)?

Totally understand if you're too busy for all this, but would be awesome debugging data if you can!

**Comment by cyrobmm** [comment] 2014-04-27 22:43
So, I changed the config as mentioned (http://screencloud.net/v/28zH) and it work (http://screencloud.net/v/yUGn). I'm just not sure about this solution. If a normal user gets this issue, we can't tell him to change something like that :). What do you think?

I tried it with Nightly and worked as well.

**Comment by shaekuronen** [comment] 2014-04-28 19:32
Awesome, good to hear this is a repeatable bug!

I'm seeing the same behavior.  The default for dom.w3c_touch_events.enabled is 0 (see [discussion](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Touch_events) at bottom of this page)

When Firefox Web Inspector is opened, Responsive Design View is selected, and Simulate touch events is selected, the value of dom.w3c_touch_events.enabled is updated to 1

This causes an error in Flexslider 

My take on this is normal users are unlikely to reproduce the bug, as it requires several actions which only developers will be taking.

In testing this issue, I found that the default Flexslider on the [demos](http://shaekuronen.github.io/jquery.flexloader/) page is also encountering the bug.  The slide animation works, but both navigation items are not working.  This is consistent with the behavior seen on the [Flexslider 2 demos](http://flexslider.woothemes.com/) page.

So, given all this, I think we'll have to wait for Flexslider to merge the fix for this issue :(

**Closed as completed** 2014-05-01 12:05 UTC
